### ISSUE TITLE
Options to Control Newlines in Nested CSS Rules

### ISSUE THREAD

**Issue by spencerbeggs** [prettydiff/prettydiff#117]
Pretty Diff rocks! I mainly use it to parse LESS and SCSS. Since those can have high level of nesting I would love to see an option to enforce/preserve newlines after a root rules and have a second option to enforce/preserve newlines inside of nested rules -- you see this a lot in Bootstrap, for instance.

Currently if `cssinsertlines=true`, this LESS:

```less
#foo {
    color: red;
    .innerFoo {
        color: blue;
        .inner2 {
            color: green;
        }
    }
}
#bar {
    color: red;
}
```

becomes:

```css
#foo {
    color: red;
    .innerFoo {
        color: blue;
        .inner2 {
            color: green;
        }

    }

}


#bar {
    color: red;
}
```

In my mind, that should look like:

```css
#foo {
    color: red;
    .innerFoo {
        color: blue;
        .inner2 {
            color: green;
        }
    }
}

#bar {
    color: red;
}
```

I also think it would be helpful to split out the option for `preserve` into a root and nested option.

We could make it so `cssinsertlines` and `preserve` and refer to the top-level rules. The corresponding settings for the nested rules would initially be set equal to the top-level rules unless explicitly overridden.

If you are game, I will take a crack at it and send you a PR and tests.
