### ISSUE TITLE
Doesn't indent @keyframes correctly in SCSS 

### ISSUE THREAD

**Issue by najela** [prettydiff/prettydiff#136]
Hello

```scss
@keyframes infinite-spinning {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

Gets beautified to

```css
@keyframes infinite-spinning {
    from {
        transform: rotate(0deg);
    }

to {
        transform: rotate(360deg);
    }
}
```

I am using [atom beautify](https://github.com/Glavin001/atom-beautify).

> CC https://github.com/Glavin001/atom-beautify/issues/500
