### ISSUE TITLE
Nested rules not indented in SCSS

### ISSUE THREAD

**Issue by ArekSredzki** [prettydiff/prettydiff#141]
Nested rules aren't indented in SCSS if the option to insert new lines between rules is checked.
This only effects the nested rules that aren't the first on that level.

Original:
```scss
header .navbar-nav {
  float: none;
}
footer {
  .navbar {
    min-height: 25px;
  }
  .other-class {
    min-height: 25px;
  }
  .other-class-2 {
    min-height: 25px;
  }
}
```

Expected:
```scss
header .navbar-nav {
  float: none;
}

footer {
  .navbar {
    min-height: 25px;
  }

  .other-class {
    min-height: 25px;
  }
  
  .other-class-2 {
    min-height: 25px;
  }
}
```

Actual:
```scss
header .navbar-nav {
  float: none;
}

footer {
  .navbar {
    min-height: 25px;
  }
  
.other-class {
    min-height: 25px;
  }
  
.other-class-2 {
    min-height: 25px;
  }
}
```
