### ISSUE TITLE
CSS objsort also sorts prefixes

### ISSUE THREAD

**Issue by jerone** [prettydiff/prettydiff#247]
If I have the following CSS code (block 1) and beautify the code with option [`objsort`](http://prettydiff.com/documentation.xhtml#objsort) enabled for CSS, all prefixes are also sorted (block 2). What I expected to see is that the prefixed properties are still grouped together (block 1), with the unprefixed standard version below it. Order of prefixes are per discussion.

Test code and expected grouping/order:

``` CSS
.example {
    border-top: 1px solid #000;

    -webkit-column-count: 2;
    -moz-column-count: 2;
    column-count: 2;

    -webkit-column-gap: 10px;
    -moz-column-gap: 10px;
    column-gap: 10px;

    -webkit-column-rule: 1px solid #000;
    -moz-column-rule: 1px solid #000;
    column-rule: 1px solid #000;
}
```

Current output:

``` CSS
.example {
    -moz-column-count: 2;
    -moz-column-gap: 10px;
    -moz-column-rule: 1px solid #000;
    -webkit-column-count: 2;
    -webkit-column-gap: 10px;
    -webkit-column-rule: 1px solid #000;
    border-top: 1px solid #000;
    column-count: 2;
    column-gap: 10px;
    column-rule: 1px solid #000;
}
```

This is also an issue for property values:

``` CSS
.example {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```

---

_I use Pretty Diff as part of [atom-beautify](https://github.com/Glavin001/atom-beautify)._
