### ISSUE TITLE
CSS preserve not working

### ISSUE THREAD

**Issue by jackocnr** [prettydiff/prettydiff#274]
Go to http://prettydiff.com

Enter the following CSS:
```css
.a {
  margin: 0;

  padding: 10px;
}
```

Make sure "Preserve empty lines" is checked and click Execute.

Expected result:
```css
.a {
  margin: 0;

  padding: 10px;
}
```

Actual result:
```css
.a {
  margin: 0;
  padding: 10px;
}
```
