### ISSUE TITLE
CSS beautify transposes !important on margin

### ISSUE THREAD

**Issue by bloopletech** [prettydiff/prettydiff#294]
Beautifying the following CSS:

````css
 .navbar-brand {
  margin-right: 20px;
  margin-left: 0 !important;
  margin-top:0.5em;
}
````

Results in the following output:

````css
.navbar-brand {
    margin-right: 20px !important;
    margin-left: 0;
    margin-top: 0.5em !important;
}
````

The `!important` on the `margin-left` is removed from the `margin-left` and added to the `margin-right` and the `margin-top`.

This is reproducible in both http://prettydiff.com and prettydiff@63250d8f27087a932033a5d15ca10b65ff9862f3 on my local machine using index.xhtml, using default settings. The prettydiff comment was:

````/*prettydiff.com mode: "beautify" */````

This looks similar to #159, and to the 2nd bullet point in #260, but that issue is apparently fixed so this looks like a new issue.
