### ISSUE TITLE
PrettyDiff Beautify CSS/SCSS: 0ms is converted to 0 (unitless).

### ISSUE THREAD

**Issue by cborchert** [prettydiff/prettydiff#463]
0 values in CSS can only be unitless for length values, not for time. 

Note that this seems only to happen with ms values that are not followed by a comma. Additionally 0s retains its unit.

The following example should illustrate the point:
```css
.test {
  transition: opacity 600ms linear 0ms, left 0ms linear 600ms, top 0s linear 0ms; 
}
```
Beautified with prettydiff becomes:
```css
.test {
    transition: opacity 600ms linear 0ms, left 0 linear 600ms, top 0s linear 0;
}
```

Expected output:
```css
.test {
    transition: opacity 600ms linear 0ms, left 0ms linear 600ms, top 0s linear 0ms;
}
```
