### ISSUE TITLE
CSS do not strip "ms" from "0ms" values

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#491]
https://github.com/Glavin001/atom-beautify/issues/1909

Relevant: https://developer.mozilla.org/en-US/docs/Web/CSS/time

```css
a {
  -webkit-transition: left 400ms ease-in-out 0ms;
  -moz-transition: left 400ms ease-in-out 0ms;
  -o-transition: left 400ms ease-in-out 0ms;
  transition: left 400ms ease-in-out 0ms;
}
```
