### ISSUE TITLE
Braces option not doing anything for CSS

### ISSUE THREAD

**Issue by stevenzeck** [prettydiff/prettydiff#509]
1. Go to prettydiff.com
2. Select Beautify and insert text `.test{font-size:12pt;}`
3. Under Multiformat Options, select **Allman (ANSI) style**

Result:
```css
.test {
    font-size: 12pt;
}
```

Expected:
```css
.test
{
    font-size: 12pt;
}
```
