### ISSUE TITLE
CSS - merging padding/margin incorrectly

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#574]
```css
.nav-item {
margin: 0 10px !important;
padding: 6px 12px !important;
padding-top: 3px !important;
}
```

https://github.com/Glavin001/atom-beautify/issues/2324
